### ISSUE TITLE
Floating options box

### ISSUE THREAD

**Issue by ancker010** [vsoch/resource-explorer#3]
Make the "Your Options" box static on the right side of the page as you scroll down to select more options.

I may look into writing some code and submitting a PR.

<---also struggles with javascript (and just about everything else)

**Comment by vsoch** [comment]
Heyo! I’m actually fixing up some bugs now and doing a little bit of re-factoring, so don’t start working on it just yet :)

**Comment by ancker010** [comment]
Insert :thumbsup: emoji.

**Comment by vsoch** [comment]
Your emoji game is strong, @ancker010 ! :muscle:

**Comment by vsoch** [comment]
Can you better explain what you mean by making it static?

**Comment by ancker010** [comment]
Sure. The "Your Options" section on the ride side scrolls up (and off) the screen as you scroll down to answer the questions. Once it is off the screen, you cannot see how the options are changing as you make selections. By "make static" I mean have the "Your Options" section remain visible on the right column as you scroll down the page. Does that make sense?

**Comment by vsoch** [comment]
yeah totally! I think my main concern there would be how it looks on mobile - right now the options are just below the questions (so you logically move through them, then see the final result at the bottom). If you are able to make the section "sticky" (I think that's what they call it) and still have a good mobile experience, I'd be good with reviewing a pull request. I think you can achieve what you are looking for with just css, and then target different media sizes to make sure the change isn't mad for mobile.

When you PR, if you want to deploy to your GitHub pages so we can look on mobile (I'll look on my phone) then we can check both.

Also - just made a bunch of fixes! https://vsoch.github.io/resource-explorer/ First, I removed all those empty selection boxes "---" in favor of a reset button that will just start fresh. There was also a major bug in the filtering - it wasn't accounting for all the choices (but now should be).

**Comment by ancker010** [comment]
Cool. I'll try to make something happen. I hadn't considered the mobile view concerns.
Javascript/CSS/etc...ahh!

D*mnit Jim, I'm an architect, not a developer!

**Comment by ancker010** [comment]
That was, umm, easier than I expected...

https://ancker010.github.io/resource-explorer/

**Comment by vsoch** [comment]
Yeah it looks good on mobile too! Could you perhaps leave about 15px of white space from the very top? Then I'd be good to review a PR :)

**Comment by ancker010** [comment]
Done. PR incoming.
